# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Screenshot
        uses: lowlighter/metrics@latest
        with:
            filename: pagespeed.screenshot.svg
            token: NOT_NEEDED
            base: "allowebs.com"
            plugin_pagespeed: yes
            plugin_pagespeed_screenshot: yes
            plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
            plugin_pagespeed_url: ${{ secrets.website }}
